In [1]:
# This file is dedicated to name entity pronounciation task. The idea is to record all the syllables of 
# Devnagari and then play them very smoothly to mimic the pronouciation of the name entity given a true 
# spelling.

In [2]:
# The way the task is achived is that
# 1. We have recorded all the Vyanjana Varnas with two different sounds. One is for the starting sound and 
# other one is with Halant mix. 
# 2. We have recorded all the Swara Varnas with properly cropped from true word pronunciations.

# Vyanjana Varnas - k kh g gh ch chh j jh t th d dh n p ph b bh m y r l w s sh - 24*2 = 48 recording (sounds).
# Swara Varnas - a aa i u e o - 6*3 = 18 , For a new accent it's 18 more sounds, that's all.


In [3]:
# Now getting the sounds. 
# Importing necessary packages
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as sk
import tensorflow as tf
import librosa
from IPython.display import Audio
import random
import soundfile as sf
import pyrubberband


2022-04-21 16:55:20.047009: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-04-21 16:55:20.047143: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [4]:
# Now we need a long audio file that will contain all the words distinctly. 

# Let's do a fine cropping program based on amplitude. 

# Importing the audio.
ar, sr = librosa.load('data/system_2/poc/ankush.wav')

print(ar.shape)
print(sr)

Audio(data=ar, rate=sr)


(18912,)
22050


In [5]:
# Let's import all of our recordings. 
file_list = os.listdir('data/system_2/sounds')
print(len(file_list))
print(file_list)


69
['g_s.wav', 'g_e.wav', 'm_e.wav', 'u_s.wav', 'k_s.wav', 'j_s.wav', 'l_s.wav', 'kh_e.wav', 'm_s.wav', 'aa_e.wav', 'j_e.wav', 'gh_e.wav', 'n_e.wav', 'y_e.wav', 'w_e.wav', 'aa_m.wav', 'w_s.wav', 'b_e.wav', 'bh_e.wav', 'e_e.wav', 'aa_s.wav', 'u_e.wav', 'dh_s.wav', 'r_e.wav', 'ph_e.wav', '_.wav', 'bh_s.wav', 'h_s.wav', 'n_s.wav', 'sh_e.wav', 'i_s.wav', 'sh_s.wav', 'o_m.wav', 'h_e.wav', 'ch_s.wav', 'e_s.wav', 'a_e.wav', 'p_e.wav', 'kh_s.wav', 't_s.wav', 't_e.wav', 'jh_e.wav', 'y_s.wav', 'ch_e.wav', 'p_s.wav', 'd_s.wav', 'chh_e.wav', 'e_m.wav', 'o_e.wav', 'b_s.wav', 'ph_s.wav', 'a_m.wav', 'th_e.wav', 's_e.wav', 'a_s.wav', 'dh_e.wav', 'd_e.wav', 'gh_s.wav', 'u_m.wav', 'chh_s.wav', 's_s.wav', 'th_s.wav', 'jh_s.wav', 'r_s.wav', 'i_e.wav', 'i_m.wav', 'k_e.wav', 'o_s.wav', 'l_e.wav']


In [6]:
sound_dict = {}

for file_name in file_list:
    inst_key = file_name.split('.')[0]
    inst_arr, inst_sr = librosa.load('data/system_2/sounds/{}'.format(file_name))
    sound_dict[inst_key] = inst_arr
    
display(sound_dict)


{'g_s': array([-1.04901493e-02, -2.35138442e-02, -2.04419214e-02, -2.35871021e-02,
        -2.41910797e-02, -2.41070557e-02, -2.66218763e-02, -2.60583833e-02,
        -2.70593613e-02, -2.77389362e-02, -2.66359858e-02, -2.50211265e-02,
        -2.48783175e-02, -2.58579738e-02, -2.33275760e-02, -2.38214079e-02,
        -2.53181811e-02, -2.42870077e-02, -2.55229715e-02, -2.51774490e-02,
        -2.71691456e-02, -2.83851642e-02, -3.08653936e-02, -3.22381780e-02,
        -3.12288217e-02, -3.40930186e-02, -3.30978222e-02, -3.29195559e-02,
        -3.24895717e-02, -2.99735572e-02, -3.01511753e-02, -2.75583006e-02,
        -2.56471802e-02, -2.81466227e-02, -2.72093806e-02, -2.60344315e-02,
        -2.65166387e-02, -2.62690373e-02, -2.76292097e-02, -2.82501765e-02,
        -2.91324183e-02, -2.86600981e-02, -2.72916723e-02, -2.71505807e-02,
        -2.56440677e-02, -2.37799119e-02, -2.33684927e-02, -2.33403258e-02,
        -2.23411694e-02, -2.28667799e-02, -2.27041375e-02, -2.08514631e-02,
     

In [7]:
# Let's play a file from the dict
sound = sound_dict['aa_e']
Audio(sound, rate=sr)


In [8]:
%%time
# Testing with the accent. 
# name = 'k_s a_s k_s a_m k_s a_e k_e'
# name = 'k_s aa_s k_s aa_m k_s aa_e k_e'
# name = 'k_s i_s k_s i_m k_s i_e k_e'
# name = 'k_s u_s k_s u_m k_s u_e k_e'
# name = 'k_s e_s k_s e_m k_s e_e k_e'
# name = 'k_s o_s k_s o_m k_s o_e k_e'

# Testing with real names. 
# name = 'n_s e_s h_s aa_s l_e'
# name = 'r_s o_s l_s e_m k_s s_e'
# name = 'r_s o_s d_e r_s i_m g_s o_e'
# name = 'r_s aa_s j_s e_m sh_e _ r_s o_s sh_s a_e n_e'
name = 'r_s aa_s j_s i_e bh_e _ l_s o_s ch_s a_e n_e _ s_s u_s b_s u_s dh_s i_e'

# Write an automatic code or this.
# name = 'k_s a_s n_e k_s a_e n_e _ r_s a_e j_e _ m_s o_s n_e d_s a_e l_e'

# Testing with complex names. 
# Name_1
# Benudharan Muralinath Chokroworti
# name = 'b_s e_s n_s u_m dh_s a_m r_s a_m n_e _ m_s u_s r_s a_m l_s i_m n_s aa_e th_e _ ch_s o_s k_e r_s o_m w_s o_m r_s t_s i_e'

# Name_2
# Mahyushmati Chatopadhyaya Vede
# name = 'm_s aa_s h_s y_s u_m sh_e m_s a_m t_s i_e _ ch_s a_s t_s o_m p_s aa_m dh_s y_s aa_m y_s a_e _ bh_s e_s d_s e_e'

# Name_3
# Rowan Philip Alex
# name = 'r_s o_s w_s a_m n_e _ ph_s i_s l_s i_e p_e _ aa_s l_s e_e k_e s_e'

# Name_4
# Xitij Patel
# name = 'k_e s_s i_s t_s i_e j_e _ p_s a_s t_s e_e l_e'

name_ar = name.split(' ')
print(name_ar)


['r_s', 'aa_s', 'j_s', 'i_e', 'bh_e', '_', 'l_s', 'o_s', 'ch_s', 'a_e', 'n_e', '_', 's_s', 'u_s', 'b_s', 'u_s', 'dh_s', 'i_e']
CPU times: user 175 µs, sys: 35 µs, total: 210 µs
Wall time: 164 µs


### Writing out the english spelling to format converter codes. 

In [9]:
vyanjana_varna_sounds = [
    'k_s', 'k_e', 'kh_s', 'kh_e', 'g_s', 'g_e', 'gh_s', 'gh_e',
    'ch_s', 'ch_e', 'chh_s', 'chh_e', 'j_s', 'j_e', 'jh_s', 'jh_e',
    't_s', 't_e', 'th_s', 'th_e', 'd_s', 'd_e', 'dh_s', 'dh_e', 'n_s', 'n_e',
    'p_s', 'p_e', 'ph_s', 'ph_e', 'b_s', 'b_e', 'bh_s', 'bh_e', 'm_s', 'm_e',
    'y_s', 'y_e', 'r_s', 'r_e', 'l_s', 'l_e', 'w_s', 'w_e', 'sh_s', 'sh_e', 's_s', 's_e', 'h_s', 'h_e'
]

vyanjana_varnas = [
    'k', 'kh', 'g', 'gh'
    # There would be more.
] 

name = 'kakakak'

name_list = list(name)
print(name_list)

for i in range(len(name_list)):
    inst_char = name_list[i]
    try:
        inst_next_char = name_list[i+1]
    except:
        pass
    






['k', 'a', 'k', 'a', 'k', 'a', 'k']


In [10]:
%%time
# Re-assembling the words.
final_voice = np.array([])

for character in name_ar:
    inst_audio_ar = sound_dict[character]
    
    if character in ['_']:  
#         inst_audio_ar = inst_audio_ar[0 : 500]
        pass 
    
    if character in ['a', 'aa', 'i', 'u', 'e', 'o']:  
        pass    
    
    else:
        # inst_audio_ar = pyrubberband.pyrb.time_stretch(inst_audio_ar, sr, 0.5, rbargs=None)
        pass
        
    final_voice = np.concatenate([final_voice, inst_audio_ar])

# Speed shifting
# final_voice = pyrubberband.pyrb.time_stretch(final_voice, sr, 1.2, rbargs=None)

# Pitch shifting
# final_voice = pyrubberband.pyrb.pitch_shift(final_voice, sr, 1, rbargs=None)

# Volume shifting
# final_voice = final_voice - 0
    
# Write the final audio.
sf.write('output_{}.wav'.format(str(2)), final_voice, int(sr*1.0), 'PCM_24')

Audio(final_voice, rate=sr)


CPU times: user 7.96 ms, sys: 763 µs, total: 8.72 ms
Wall time: 10.1 ms


In [11]:
# So what's the problem with the pronunciation.
# j sound is too deep. n sound is not properly cropped. f

In [12]:
# What should be done in production.

# In production we first need to match the accent with the main flow of the all the sentences and then 
# pronounce all the names. We need to pronounce real names for all the Vyanjana Varnas and finely crop all 
# the starting and ending Vyanjana Varnas.

#Then we need to tell and accent and then finely crop all the Swaravarna Sounds used in that accent. Even 
# more better way is to crop all the Swaravarna Sounds from the real name pronunciations and create the accents 
# with the ka kaa ki ku ke ko sound later to show the accent.   

# All the sounds of Vyranjana Varnas, Swaravarnas should be recorded from the words spoken with the main sentence
# accent in one shot.

# Then one need to test all the small sound chunks with while doing the original names by the system and see by
# himself that all the sounds are properly croped. 

# Then we need to create a dictionary for mapping the main spelling with the pronounciable spelling. 


### Here we will do a code for audio processing for TTS System 2. Here we are writing the fine cropping algorithm.

In [13]:
# Importing the audio.
ar, sr = librosa.load('data/system_2/audio_take_inst.wav')

Audio(ar, rate=sr)


In [14]:
# Now the next thing to do is to get the first sound.
ar_inst, sr_inst = librosa.load('data/system_2/audio_take_inst.wav', duration=16.0)

print(ar_inst)
print(len(ar_inst))
print(22050*8)

crop_amp_threshold = 16
analysis_time_gap = 256

# Splitting the ar_inst
intervals = librosa.effects.split(ar_inst, top_db=int(crop_amp_threshold), frame_length=int(int(analysis_time_gap)*0.001*int(sr_inst)))
print(intervals)
print(len(intervals))

# For listening to the sounds
# Audio(ar_inst, rate=sr_inst)

[-1.0792799e-07  2.0037762e-06 -3.6946331e-06 ... -6.9773063e-02
 -6.7802884e-02 -7.3194712e-02]
352800
176400
[[ 83456  90624]
 [129024 135680]
 [171520 179712]
 [215552 224256]
 [260608 267776]
 [304640 312320]
 [348672 352800]]
7


In [15]:
first_index = intervals[0][0] - (0.2*sr_inst) 
print(first_index)

start_index = int(first_index)
end_index = int(intervals[0][1] + (0.2*sr_inst))
chunk_gap = end_index - start_index

print(start_index, end_index)
# Playing from start_index to end_index
Audio(ar_inst[start_index : end_index], rate=sr_inst)

# Going for the next index. 
metronome_gap = 2 * sr_inst

start_index = start_index + 6*metronome_gap
end_index = start_index + chunk_gap

Audio(ar_inst[start_index : end_index], rate=sr_inst)

79046.0
79046 95034


In [16]:
# Now it's time to do a fine cropping
# For fine croppping we need to change the analysis time gap to 64. Let's try with that.
fine_crop_amp_threshold = 16
fine_analysis_time_gap = 128

inst_sound_chunk = ar_inst[start_index : end_index]
intervals = librosa.effects.split(inst_sound_chunk, top_db=int(fine_crop_amp_threshold), frame_length=int(int(fine_analysis_time_gap)*0.001*int(sr_inst)))

print(intervals)



[[5632 9154]]


### Research regarding fine cropping of Vyanjana Varnas

In [30]:
# k_s k_e kk kak ka ak 

ar, sr = librosa.load('data/system_2/g.wav', sr=None)
print(ar, sr)

intervals = librosa.effects.split(ar, top_db=4)
print(intervals)


Audio(ar[intervals[1][0] : intervals[1][1]], rate=sr)


[-0.08224487 -0.08253479 -0.08218384 ...  0.03852844  0.04003906
  0.04112244] 48000
[[    0  1536]
 [68096 74240]]
